<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.24">
  <POU Name="FB_CsvLogger" Id="{70384420-e74f-4fa1-99ae-a5d53b513001}">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK FB_CsvLogger IMPLEMENTS ILogger 
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Write" Id="{0102a398-3b21-44df-a24d-a15952023b0d}">
      <Declaration><![CDATA[METHOD PUBLIC Write : STRING
VAR_INPUT
	sMsg      : STRING;
END_VAR

]]></Declaration>
      <Implementation>
        <ST><![CDATA[Write := CONCAT('csv-', sMsg);
// open csv file
// write the message into the csv file
// close csv file]]></ST>
      </Implementation>
    </Method>
    <ObjectProperties />
  </POU>
</TcPlcObject>