<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.24">
  <POU Name="FB_XmlLogger" Id="{142f02b9-70fe-4235-8d7b-5808e6dd12dc}">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK FB_XmlLogger IMPLEMENTS ILogger
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Write" Id="{88070c92-1819-408a-9ef0-7aa749e9dc72}">
      <Declaration><![CDATA[METHOD PUBLIC Write : STRING
VAR_INPUT
	sMsg      : STRING;
END_VAR

]]></Declaration>
      <Implementation>
        <ST><![CDATA[Write := CONCAT('xml-', sMsg);
// open xml file
// write the message into the xml file
// close xml file
]]></ST>
      </Implementation>
    </Method>
    <ObjectProperties />
  </POU>
</TcPlcObject>