<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.24">
  <POU Name="MAIN" Id="{fd6e49ae-9c60-4ba4-ba01-45f20a4b6c2c}">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbLogger 		: FB_Logger('File.csv');
	retMsg			: STRING;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[retMsg := fbLogger.Write('Hello');]]></ST>
    </Implementation>
    <ObjectProperties />
  </POU>
</TcPlcObject>